// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnfcjudrblqpfvmjfubm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZmNqdWRyYmxxcGZ2bWpmdWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODE2NTEsImV4cCI6MjA3MjM1NzY1MX0.xyVDxKcl5vYLXA9XJr5m8zajKFGY2y37D048Zz7WB20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});